# Site settings
title: No0b Tech
email: dstanfield.esq@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. Woop. Woop. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://sputterputtredux.github.io/index.html" # the base hostname & protocol for your site
twitter_username: dionnestanfield
github_username:  SputterPuttRedux

# Build settings
markdown: kramdown
